/*!
* Qoopido.js library package
*
* version: 3.1.0
* date:    2013-10-02
* author:  Dirk Lueth <info@qoopido.com>
* website: https://github.com/dlueth/qoopido.js
*
* Copyright (c) 2013 Dirk Lueth
*
* Dual licensed under the MIT and GPL licenses.
*  - http://www.opensource.org/licenses/mit-license.php
*  - http://www.gnu.org/copyleft/gpl.html
*/
(function(t){"use strict";"function"==typeof define&&define.amd?define(t):t()})(function(){"use strict";if(!Object.defineProperty||!function(){try{return Object.defineProperty({},"x",{}),!0}catch(t){return!1}}()){var t=Object.defineProperty,e=Object.prototype.__defineGetter__,n=Object.prototype.__defineSetter__;Object.defineProperty=function(i,r,o){if(t)try{return t(i,r,o)}catch(a){}if(i!==Object(i))throw new TypeError("Object.defineProperty called on non-object");return e&&"get"in o&&e.call(i,r,o.get),n&&"set"in o&&n.call(i,r,o.set),"value"in o&&(i[r]=o.value),i}}});
(function(t){"use strict";if("function"==typeof define&&define.amd){var e=[];Object.defineProperty&&function(){try{return Object.defineProperty({},"x",{}),!0}catch(t){return!1}}()||e.push("./defineproperty"),define(e,t)}else t()})(function(){"use strict";Object.defineProperties||(Object.defineProperties=function(t,e){if(t!==Object(t))throw new TypeError("Object.defineProperties called on non-object");var n;for(n in e)Object.prototype.hasOwnProperty.call(e,n)&&Object.defineProperty(t,n,e[n]);return t})});
(function(t){"use strict";if("function"==typeof define&&define.amd){var e=[];Object.defineProperties||e.push("./defineproperties"),define(e,t)}else t()})(function(){"use strict";Object.create||(Object.create=function(t,e){function n(){}if("object"!=typeof t)throw new TypeError;n.prototype=t;var i=new n;if(t&&(i.constructor=n),arguments.length>1){if(e!==Object(e))throw new TypeError;Object.defineProperties(i,e)}return i})});
(function(t){"use strict";"function"==typeof define&&define.amd?define(t):t()})(function(){"use strict";if(!Object.getOwnPropertyDescriptor||!function(){try{return Object.getOwnPropertyDescriptor({x:0},"x"),!0}catch(t){return!1}}()){var t=Object.getOwnPropertyDescriptor;Object.getOwnPropertyDescriptor=function(e,n){if(e!==Object(e))throw new TypeError;try{return t.call(Object,e,n)}catch(i){}return Object.prototype.hasOwnProperty.call(e,n)?{value:e[n],enumerable:!0,writable:!0,configurable:!0}:void 0}}});
(function(e,t,r,n){"use strict";function c(e,c,o,i){var u=e.split("/");return s[e]?s[e]:(o=o?[].slice.call(o,0):[],s[e]=function(){return i===!0?c.call(null,s,o,u,t,r,n).create():c.call(null,s,o,u,t,r,n)}())}function o(){return c("base",e)}var i="qoopido",u=t[i]=t[i]||{initialize:c},s=(u.shared=u.shared||{},u.modules=u.modules||{});if("function"==typeof define&&define.amd){var a=[];Object.create||a.push("./polyfill/object/create"),Object.getOwnPropertyNames||a.push("./polyfill/object/getownpropertynames"),Object.getOwnPropertyDescriptor&&function(){try{return Object.getOwnPropertyDescriptor({x:0},"x"),!0}catch(e){return!1}}()||a.push("./polyfill/object/getownpropertydescriptor"),define(a,o)}else o()})(function(e,t,r,n,c,o){"use strict";function i(e){var t,r,n={},c=Object.getOwnPropertyNames(e);for(t=0;(r=c[t])!==o;t++)n[r]=Object.getOwnPropertyDescriptor(e,r);return n}return{create:function(){var e,t=Object.create(this,i(this));return t._constructor&&(e=t._constructor.apply(t,arguments)),t.create=t.extend=o,e||t},extend:function(e){return e=e||{},e._parent=this,Object.create(this,i(e))}}},window,document);
(function(t,e){"use strict";function n(){return e.qoopido.initialize("emitter",t,arguments)}"function"==typeof define&&define.amd?define(["./base"],n):n()})(function(t,e,n,i,r,o){"use strict";function a(t,e){var n=e.charAt(0).toUpperCase()+e.slice(1);return t._mapped[e]=t[e],function(){var i,r=Array.prototype.slice.call(arguments);return t.emit.apply(t,["pre"+n,r]),i=t._mapped[e].apply(t,r),t.emit.apply(t,["post"+n,r,i]),i}}var l=/^(_|extend$|create$|on$|one$|off$|emit$|get.+)/;return t.base.extend({_mapped:null,_listener:null,_constructor:function(){var t,e=this;e._listener={},e._mapped={};for(t in e)"function"==typeof e[t]&&l.test(t)===!1&&(e[t]=a(e,t))},on:function(t,e){var n,i,r=this;for(t=t.split(" "),n=0;(i=t[n])!==o;n++)(r._listener[i]=r._listener[i]||[]).push(e);return r},one:function(t,e,n){n=n!==!1;var i=this;return i.on(t,function r(o){i.off(n===!0?o:t,r),e.apply(this,arguments)}),i},off:function(t,e){var n,i,r,a,l=this;if(t)for(t=t.split(" "),n=0;(i=t[n])!==o;n++)if(l._listener[i]=l._listener[i]||[],e)for(r=0;(a=l._listener[i][r])!==o;r++)a===e&&(l._listener[i].splice(r,1),r--);else l._listener[i].length=0;else for(i in l._listener)l._listener[i].length=0;return l},emit:function(t){var e,n,i=this;if(t!==o)for(i._listener[t]=i._listener[t]||[],e=0;(n=i._listener[t][e])!==o;e++)n.apply(i,arguments);return i}})},window);
(function(t,e){"use strict";function n(){return e.qoopido.initialize("component/remux",t,arguments,!0)}"function"==typeof define&&define.amd?define(["../emitter"],n):n()})(function(t,e,n,i,r){"use strict";function a(){var t=this;return c.fontsize=parseInt(i.getComputedStyle(u).getPropertyValue("font-size"),10),c.layout=i.getComputedStyle(u,":after").getPropertyValue("content")||null,(c.fontsize!==f.fontsize||c.layout!==f.layout)&&(f.fontsize=c.fontsize,f.layout=c.layout,c.ratio.device=i.devicePixelRatio||1,c.ratio.fontsize=c.fontsize/l,c.ratio.total=c.ratio.device*c.ratio.fontsize,t.emit("statechange",c)),t}var o,s,u=r.getElementsByTagName("html")[0],l=16,c={fontsize:null,layout:null,ratio:{}},f={fontsize:null,layout:null},d=null;return o=t.emitter.extend({_constructor:function(){var t=this,e=parseInt(u.getAttribute("data-base"),10),n=function n(){null!==d&&i.clearTimeout(d),d=i.setTimeout(function(){a.call(t)},20)};o._parent._constructor.call(t),isNaN(e)===!1&&(l=e),s=r.createElement("style"),s.type="text/css",r.getElementsByTagName("head")[0].appendChild(s),i.addEventListener("resize",n,!1),i.addEventListener("orientationchange",n,!1),a.call(t)},getState:function(){return c},addLayout:function(t,e){var n,i,o,u,c,f,d=this;arguments.length>1?(n={},n[t]=e):n=arguments[0];for(i in n)for(o=n[i],u=o.min;o.max>=u;u++)c=Math.round(o.width*(u/l)),f="@media screen and (min-width: "+c+"px) { html { font-size: "+u+'px; } html:after { content: "'+i+'"; display: none; } }',s.styleSheet?s.styleSheet.cssText+=f:s.appendChild(r.createTextNode(f));return a.call(d),d}})},window);