/*!
* Qoopido.js library package
*
* version: 3.1.2
* date:    2013-10-18
* author:  Dirk Lueth <info@qoopido.com>
* website: https://github.com/dlueth/qoopido.js
*
* Copyright (c) 2013 Dirk Lueth
*
* Dual licensed under the MIT and GPL licenses.
*  - http://www.opensource.org/licenses/mit-license.php
*  - http://www.gnu.org/copyleft/gpl.html
*/
(function(t){window.qoopido.register("polyfill/object/defineproperty",t)})(function(){"use strict";if(!Object.defineProperty||!function(){try{return Object.defineProperty({},"x",{}),!0}catch(t){return!1}}()){var t=Object.defineProperty,e=Object.prototype.__defineGetter__,n=Object.prototype.__defineSetter__;Object.defineProperty=function(r,i,o){if(t)try{return t(r,i,o)}catch(s){}if(r!==Object(r))throw new TypeError("Object.defineProperty called on non-object");return e&&"get"in o&&e.call(r,i,o.get),n&&"set"in o&&n.call(r,i,o.set),"value"in o&&(r[i]=o.value),r}}return!0});
(function(t){var e=[];Object.defineProperty&&function(){try{return Object.defineProperty({},"x",{}),!0}catch(t){return!1}}()||e.push("./defineproperty"),window.qoopido.register("polyfill/object/defineproperties",t,e)})(function(){"use strict";return Object.defineProperties||(Object.defineProperties=function(t,e){if(t!==Object(t))throw new TypeError("Object.defineProperties called on non-object");var n;for(n in e)Object.prototype.hasOwnProperty.call(e,n)&&Object.defineProperty(t,n,e[n]);return t}),!0});
(function(t){var e=[];Object.defineProperties||e.push("./defineproperties"),window.qoopido.register("polyfill/object/create",t,e)})(function(){"use strict";return Object.create||(Object.create=function(t,e){function n(){}if("object"!=typeof t)throw new TypeError;n.prototype=t;var r=new n;if(t&&(r.constructor=n),arguments.length>1){if(e!==Object(e))throw new TypeError;Object.defineProperties(r,e)}return r}),!0});
(function(t){window.qoopido.register("polyfill/object/getownpropertydescriptor",t)})(function(){"use strict";if(!Object.getOwnPropertyDescriptor||!function(){try{return Object.getOwnPropertyDescriptor({x:0},"x"),!0}catch(t){return!1}}()){var t=Object.getOwnPropertyDescriptor;Object.getOwnPropertyDescriptor=function(e,n){if(e!==Object(e))throw new TypeError;try{return t.call(Object,e,n)}catch(r){}return Object.prototype.hasOwnProperty.call(e,n)?{value:e[n],enumerable:!0,writable:!0,configurable:!0}:undefined}}return!0});
(function(e,t,r,n,o){"use strict";function c(e,c,i,u){var p,f=e.split("/");return a[e]?a[e]:(p=function(){if(i){var p,l,g=f.slice(0,-1).join("/");for(p=0;(l=i[p])!==o;p++)d.test(l)&&(l=s(g+"/"+l)),!a[l]&&arguments[p]&&(a[l]=arguments[p]),a[l]||"undefined"==typeof console||console.error("".concat("[Qoopido.js] ",e,": Could not load dependency ",l))}return a[e]=c(a,f,t,r,n,o),u&&u(a[e]),a[e]},"function"==typeof define&&define.amd?i?define(i,p):define(p):p(),o)}function i(e,t,r){c(e,t,r,function(t){a[e]=t.create()})}function s(e){for(var t;(t=e.replace(l,""))!==e;)e=t;return e.replace(g,"")}var u="qoopido",p=r[u]=r[u]||{register:c,registerSingleton:i},a=(p.shared=p.shared||{},p.modules=p.modules||{}),f=[],d=RegExp("^\\.+\\/"),l=RegExp("(?:\\/|)[^\\/]*\\/\\.\\."),g=RegExp("(^\\/)|\\.\\/","g");Object.create||f.push("./polyfill/object/create"),Object.getOwnPropertyNames||f.push("./polyfill/object/getownpropertynames"),Object.getOwnPropertyDescriptor&&function(){try{return Object.getOwnPropertyDescriptor({x:0},"x"),!0}catch(e){return!1}}()||f.push("./polyfill/object/getownpropertydescriptor"),c("base",e,f)})(function(e,t,r,n,o,c){"use strict";function i(e){var t,r,n={},o=Object.getOwnPropertyNames(e);for(t=0;(r=o[t])!==c;t++)n[r]=Object.getOwnPropertyDescriptor(e,r);return n}return{create:function(){var e,t=Object.create(this,i(this));return t._constructor&&(e=t._constructor.apply(t,arguments)),t.create=t.extend=c,e||t},extend:function(e){return e=e||{},e._parent=this,Object.create(this,i(e))}}},navigator,window,document);
(function(t){window.qoopido.register("emitter",t,["./base"])})(function(t,e,n,r,i,o){"use strict";function a(t,e){var n=e.charAt(0).toUpperCase()+e.slice(1);return t._mapped[e]=t[e],function(){var r,i=Array.prototype.slice.call(arguments);return t.emit.apply(t,["pre"+n,i]),r=t._mapped[e].apply(t,i),t.emit.apply(t,["post"+n,i,r]),r}}var l=/^(_|extend$|create$|on$|one$|off$|emit$|get.+)/;return t.base.extend({_mapped:null,_listener:null,_constructor:function(){var t,e=this;e._listener={},e._mapped={};for(t in e)"function"==typeof e[t]&&l.test(t)===!1&&(e[t]=a(e,t))},on:function(t,e){var n,r,i=this;for(t=t.split(" "),n=0;(r=t[n])!==o;n++)(i._listener[r]=i._listener[r]||[]).push(e);return i},one:function(t,e,n){n=n!==!1;var r=this;return r.on(t,function i(o){r.off(n===!0?o:t,i),e.apply(this,arguments)}),r},off:function(t,e){var n,r,i,a,l=this;if(t)for(t=t.split(" "),n=0;(r=t[n])!==o;n++)if(l._listener[r]=l._listener[r]||[],e)for(i=0;(a=l._listener[r][i])!==o;i++)a===e&&(l._listener[r].splice(i,1),i--);else l._listener[r].length=0;else for(r in l._listener)l._listener[r].length=0;return l},emit:function(t){var e,n,r=this;if(t!==o)for(r._listener[t]=r._listener[t]||[],e=0;(n=r._listener[t][e])!==o;e++)n.apply(r,arguments);return r}})});
(function(t){window.qoopido.registerSingleton("component/remux",t,["../emitter"])})(function(t,e,n,r,i){"use strict";function o(){var t=this;return c.fontsize=parseInt(r.getComputedStyle(u).getPropertyValue("font-size"),10),c.layout=r.getComputedStyle(u,":after").getPropertyValue("content")||null,(c.fontsize!==f.fontsize||c.layout!==f.layout)&&(f.fontsize=c.fontsize,f.layout=c.layout,c.ratio.device=r.devicePixelRatio||1,c.ratio.fontsize=c.fontsize/l,c.ratio.total=c.ratio.device*c.ratio.fontsize,t.emit("statechange",c)),t}var a,s,u=i.getElementsByTagName("html")[0],l=16,c={fontsize:null,layout:null,ratio:{}},f={fontsize:null,layout:null},d=null;return a=t.emitter.extend({_constructor:function(){var t=this,e=parseInt(u.getAttribute("data-base"),10),n=function n(){null!==d&&r.clearTimeout(d),d=r.setTimeout(function(){o.call(t)},20)};a._parent._constructor.call(t),isNaN(e)===!1&&(l=e),s=i.createElement("style"),s.type="text/css",i.getElementsByTagName("head")[0].appendChild(s),r.addEventListener("resize",n,!1),r.addEventListener("orientationchange",n,!1),o.call(t)},getState:function(){return c},addLayout:function(t,e){var n,r,a,u,c,f,d=this;arguments.length>1?(n={},n[t]=e):n=arguments[0];for(r in n)for(a=n[r],u=a.min;a.max>=u;u++)c=Math.round(a.width*(u/l)),f="@media screen and (min-width: "+c+"px) { html { font-size: "+u+'px; } html:after { content: "'+r+'"; display: none; } }',s.styleSheet?s.styleSheet.cssText+=f:s.appendChild(i.createTextNode(f));return o.call(d),d}})});