/*!
* Qoopido.js library package
*
* version: 3.2.0
* date:    2014-01-08
* author:  Dirk Lueth <info@qoopido.com>
* website: https://github.com/dlueth/qoopido.js
*
* Copyright (c) 2014 Dirk Lueth
*
* Dual licensed under the MIT and GPL licenses.
*  - http://www.opensource.org/licenses/mit-license.php
*  - http://www.gnu.org/copyleft/gpl.html
*/
(function(t){var e=window.qoopido=window.qoopido||{};e.register?e.register("polyfill/object/defineproperty",t):(window.qoopido.modules=window.qoopido.modules||{})["polyfill/object/defineproperty"]=t()})(function(){"use strict";if(!Object.defineProperty||!function(){try{return Object.defineProperty({},"x",{}),!0}catch(t){return!1}}()){var t=Object.defineProperty,e=Object.prototype.__defineGetter__,n=Object.prototype.__defineSetter__;Object.defineProperty=function(r,o,i){if(t)try{return t(r,o,i)}catch(s){}if(r!==Object(r))throw new TypeError("Object.defineProperty called on non-object");return e&&"get"in i&&e.call(r,o,i.get),n&&"set"in i&&n.call(r,o,i.set),"value"in i&&(r[o]=i.value),r}}return!0});
(function(t){var e=window.qoopido=window.qoopido||{};if(e.register){var n=[];Object.defineProperty&&function(){try{return Object.defineProperty({},"x",{}),!0}catch(t){return!1}}()||n.push("./defineproperty"),e.register("polyfill/object/defineproperties",t,n)}else(window.qoopido.modules=window.qoopido.modules||{})["polyfill/object/defineproperties"]=t()})(function(){"use strict";return Object.defineProperties||(Object.defineProperties=function(t,e){if(t!==Object(t))throw new TypeError("Object.defineProperties called on non-object");var n;for(n in e)Object.prototype.hasOwnProperty.call(e,n)&&Object.defineProperty(t,n,e[n]);return t}),!0});
(function(t){var e=window.qoopido=window.qoopido||{};if(e.register){var n=[];Object.defineProperties||n.push("./defineproperties"),e.register("polyfill/object/create",t,n)}else(window.qoopido.modules=window.qoopido.modules||{})["polyfill/object/create"]=t()})(function(){"use strict";return Object.create||(Object.create=function(t,e){function n(){}if("object"!=typeof t)throw new TypeError;n.prototype=t;var r=new n;if(t&&(r.constructor=n),arguments.length>1){if(e!==Object(e))throw new TypeError;Object.defineProperties(r,e)}return r}),!0});
(function(t){var e=window.qoopido=window.qoopido||{};e.register?e.register("polyfill/object/getownpropertydescriptor",t):(window.qoopido.modules=window.qoopido.modules||{})["polyfill/object/getownpropertydescriptor"]=t()})(function(){"use strict";if(!Object.getOwnPropertyDescriptor||!function(){try{return Object.getOwnPropertyDescriptor({x:0},"x"),!0}catch(t){return!1}}()){var t=Object.getOwnPropertyDescriptor;Object.getOwnPropertyDescriptor=function(e,n){if(e!==Object(e))throw new TypeError;try{return t.call(Object,e,n)}catch(r){}return Object.prototype.hasOwnProperty.call(e,n)?{value:e[n],enumerable:!0,writable:!0,configurable:!0}:undefined}}return!0});
(function(e,t,r,n,o){"use strict";function c(e,c,i,u){var a,d=e.split("/");return f[e]?f[e]:(a=function(){if(i){var a,g,y,j=d.slice(0,-1).join("/");for(a=0;(g=i[a])!==o;a++)y=l.test(g),y&&(g=s(j+"/"+g)),!f[g]&&arguments[a]&&(f[g]=arguments[a]),y&&!f[g]&&"undefined"!=typeof console&&console.error("".concat("[Qoopido.js] ",e,": Could not load dependency ",g))}return f[e]=c(f,p,d,t,r,n,o),u&&u(f[e]),f[e]},"function"==typeof define&&define.amd?i?define(i,a):define(a):a(),o)}function i(e,t,r){c(e,t,r,function(t){f[e]=t.create()})}function s(e){for(var t;(t=e.replace(g,""))!==e;)e=t;return e.replace(y,"")}var u="qoopido",a=r[u]=r[u]||{},p=a.shared=a.shared||{},f=a.modules=a.modules||{},d=[],l=RegExp("^\\.+\\/"),g=RegExp("(?:\\/|)[^\\/]*\\/\\.\\."),y=RegExp("(^\\/)|\\.\\/","g");a.register=c,a.registerSingleton=i,Object.create||d.push("./polyfill/object/create"),Object.getOwnPropertyNames||d.push("./polyfill/object/getownpropertynames"),Object.getOwnPropertyDescriptor&&function(){try{return Object.getOwnPropertyDescriptor({x:0},"x"),!0}catch(e){return!1}}()||d.push("./polyfill/object/getownpropertydescriptor"),c("base",e,d)})(function(e,t,r,n,o,c,i){"use strict";function s(e){var t,r,n={},o=Object.getOwnPropertyNames(e);for(t=0;(r=o[t])!==i;t++)n[r]=Object.getOwnPropertyDescriptor(e,r);return n}function u(){"undefined"!=typeof console&&console.error("[Qoopido.js] Operation prohibited on an actual instance")}return{create:function(){var e,t=Object.create(this,s(this));return t._constructor&&(e=t._constructor.apply(t,arguments)),t.create=t.extend=u,e||t},extend:function(e){return e=e||{},e._parent=this,Object.create(this,s(e))}}},navigator,window,document);
(function(t){window.qoopido.register("emitter",t,["./base"])})(function(t,e,n,r,i,o,a){"use strict";function l(t,e){var n=e.charAt(0).toUpperCase()+e.slice(1);return t._mapped[e]=t[e],function(){var r,i=Array.prototype.slice.call(arguments);return t.emit.apply(t,["pre"+n,i]),r=t._mapped[e].apply(t,i),t.emit.apply(t,["post"+n,i,r]),r}}var s=/^(_|extend$|create$|on$|one$|off$|emit$|get.+)/;return t.base.extend({_mapped:null,_listener:{},_constructor:function(){var t,e=this;e._mapped={};for(t in e)"function"==typeof e[t]&&s.test(t)===!1&&(e[t]=l(e,t))},on:function(t,e){var n,r,i=this;for(t=t.split(" "),n=0;(r=t[n])!==a;n++)(i._listener[r]=i._listener[r]||[]).push(e);return i},one:function(t,e,n){n=n!==!1;var r=this;return r.on(t,function i(o){r.off(n===!0?o:t,i),e.apply(this,arguments)}),r},off:function(t,e){var n,r,i,o,l=this;if(t)for(t=t.split(" "),n=0;(r=t[n])!==a;n++)if(l._listener[r]=l._listener[r]||[],e)for(i=0;(o=l._listener[r][i])!==a;i++)o===e&&(l._listener[r].splice(i,1),i--);else l._listener[r].length=0;else for(r in l._listener)l._listener[r].length=0;return l},emit:function(t){var e,n,r=this;if(t!==a)for(r._listener[t]=r._listener[t]||[],e=0;(n=r._listener[t][e])!==a;e++)n.apply(r,arguments);return r}})});
(function(t){window.qoopido.registerSingleton("component/remux",t,["../emitter"])})(function(t,e,n,r,o,i){"use strict";function a(){var t=this;return d.fontsize=parseInt(o.getComputedStyle(c).getPropertyValue("font-size"),10),d.layout=o.getComputedStyle(c,":after").getPropertyValue("content")||null,(d.fontsize!==f.fontsize||d.layout!==f.layout)&&(f.fontsize=d.fontsize,f.layout=d.layout,d.ratio.device=o.devicePixelRatio||1,d.ratio.fontsize=d.fontsize/l,d.ratio.total=d.ratio.device*d.ratio.fontsize,t.emit("statechange",d)),t}var s,u,c=i.getElementsByTagName("html")[0],l=16,d={fontsize:null,layout:null,ratio:{}},f={fontsize:null,layout:null},p=null;return s=t.emitter.extend({_constructor:function(){var t=this,e=parseInt(c.getAttribute("data-base"),10),n=function n(){null!==p&&o.clearTimeout(p),p=o.setTimeout(function(){a.call(t)},20)};s._parent._constructor.call(t),isNaN(e)===!1&&(l=e),u=i.createElement("style"),u.type="text/css",i.getElementsByTagName("head")[0].appendChild(u),o.addEventListener("resize",n,!1),o.addEventListener("orientationchange",n,!1),a.call(t)},getState:function(){return d},addLayout:function(t,e){var n,r,o,s,c,d,f=this;arguments.length>1?(n={},n[t]=e):n=arguments[0];for(r in n)for(o=n[r],s=o.min;o.max>=s;s++)c=Math.round(o.width*(s/l)),d="@media screen and (min-width: "+c+"px) { html { font-size: "+s+'px; } html:after { content: "'+r+'"; display: none; } }',u.styleSheet?u.styleSheet.cssText+=d:u.appendChild(i.createTextNode(d));return a.call(f),f}})});