/*!
* Qoopido.js library package
*
* version: 3.1.6
* date:    2013-12-21
* author:  Dirk Lueth <info@qoopido.com>
* website: https://github.com/dlueth/qoopido.js
*
* Copyright (c) 2013 Dirk Lueth
*
* Dual licensed under the MIT and GPL licenses.
*  - http://www.opensource.org/licenses/mit-license.php
*  - http://www.gnu.org/copyleft/gpl.html
*/
(function(t){var e=window.qoopido=window.qoopido||{};e.register?e.register("polyfill/object/defineproperty",t):(window.qoopido.modules=window.qoopido.modules||{})["polyfill/object/defineproperty"]=t()})(function(){"use strict";if(!Object.defineProperty||!function(){try{return Object.defineProperty({},"x",{}),!0}catch(t){return!1}}()){var t=Object.defineProperty,e=Object.prototype.__defineGetter__,n=Object.prototype.__defineSetter__;Object.defineProperty=function(r,i,o){if(t)try{return t(r,i,o)}catch(s){}if(r!==Object(r))throw new TypeError("Object.defineProperty called on non-object");return e&&"get"in o&&e.call(r,i,o.get),n&&"set"in o&&n.call(r,i,o.set),"value"in o&&(r[i]=o.value),r}}return!0});
(function(t){var e=window.qoopido=window.qoopido||{};if(e.register){var n=[];Object.defineProperty&&function(){try{return Object.defineProperty({},"x",{}),!0}catch(t){return!1}}()||n.push("./defineproperty"),e.register("polyfill/object/defineproperties",t,n)}else(window.qoopido.modules=window.qoopido.modules||{})["polyfill/object/defineproperties"]=t()})(function(){"use strict";return Object.defineProperties||(Object.defineProperties=function(t,e){if(t!==Object(t))throw new TypeError("Object.defineProperties called on non-object");var n;for(n in e)Object.prototype.hasOwnProperty.call(e,n)&&Object.defineProperty(t,n,e[n]);return t}),!0});
(function(t){var e=window.qoopido=window.qoopido||{};if(e.register){var n=[];Object.defineProperties||n.push("./defineproperties"),e.register("polyfill/object/create",t,n)}else(window.qoopido.modules=window.qoopido.modules||{})["polyfill/object/create"]=t()})(function(){"use strict";return Object.create||(Object.create=function(t,e){function n(){}if("object"!=typeof t)throw new TypeError;n.prototype=t;var r=new n;if(t&&(r.constructor=n),arguments.length>1){if(e!==Object(e))throw new TypeError;Object.defineProperties(r,e)}return r}),!0});
(function(t){var e=window.qoopido=window.qoopido||{};e.register?e.register("polyfill/object/getownpropertydescriptor",t):(window.qoopido.modules=window.qoopido.modules||{})["polyfill/object/getownpropertydescriptor"]=t()})(function(){"use strict";if(!Object.getOwnPropertyDescriptor||!function(){try{return Object.getOwnPropertyDescriptor({x:0},"x"),!0}catch(t){return!1}}()){var t=Object.getOwnPropertyDescriptor;Object.getOwnPropertyDescriptor=function(e,n){if(e!==Object(e))throw new TypeError;try{return t.call(Object,e,n)}catch(r){}return Object.prototype.hasOwnProperty.call(e,n)?{value:e[n],enumerable:!0,writable:!0,configurable:!0}:undefined}}return!0});
(function(e,t,r,n,o){"use strict";function c(e,c,i,u){var p,d=e.split("/");return f[e]?f[e]:(p=function(){if(i){var p,g,y,j=d.slice(0,-1).join("/");for(p=0;(g=i[p])!==o;p++)y=l.test(g),y&&(g=s(j+"/"+g)),!f[g]&&arguments[p]&&(f[g]=arguments[p]),y&&!f[g]&&"undefined"!=typeof console&&console.error("".concat("[Qoopido.js] ",e,": Could not load dependency ",g))}return f[e]=c(f,a,d,t,r,n,o),u&&u(f[e]),f[e]},"function"==typeof define&&define.amd?i?define(i,p):define(p):p(),o)}function i(e,t,r){c(e,t,r,function(t){f[e]=t.create()})}function s(e){for(var t;(t=e.replace(g,""))!==e;)e=t;return e.replace(y,"")}var u="qoopido",p=r[u]=r[u]||{},a=p.shared=p.shared||{},f=p.modules=p.modules||{},d=[],l=RegExp("^\\.+\\/"),g=RegExp("(?:\\/|)[^\\/]*\\/\\.\\."),y=RegExp("(^\\/)|\\.\\/","g");p.register=c,p.registerSingleton=i,Object.create||d.push("./polyfill/object/create"),Object.getOwnPropertyNames||d.push("./polyfill/object/getownpropertynames"),Object.getOwnPropertyDescriptor&&function(){try{return Object.getOwnPropertyDescriptor({x:0},"x"),!0}catch(e){return!1}}()||d.push("./polyfill/object/getownpropertydescriptor"),c("base",e,d)})(function(e,t,r,n,o,c,i){"use strict";function s(e){var t,r,n={},o=Object.getOwnPropertyNames(e);for(t=0;(r=o[t])!==i;t++)n[r]=Object.getOwnPropertyDescriptor(e,r);return n}return{create:function(){var e,t=Object.create(this,s(this));return t._constructor&&(e=t._constructor.apply(t,arguments)),t.create=t.extend=i,e||t},extend:function(e){return e=e||{},e._parent=this,Object.create(this,s(e))}}},navigator,window,document);
(function(t){window.qoopido.register("emitter",t,["./base"])})(function(t,e,n,r,i,o,a){"use strict";function l(t,e){var n=e.charAt(0).toUpperCase()+e.slice(1);return t._mapped[e]=t[e],function(){var r,i=Array.prototype.slice.call(arguments);return t.emit.apply(t,["pre"+n,i]),r=t._mapped[e].apply(t,i),t.emit.apply(t,["post"+n,i,r]),r}}var s=/^(_|extend$|create$|on$|one$|off$|emit$|get.+)/;return t.base.extend({_mapped:null,_listener:{},_constructor:function(){var t,e=this;e._mapped={};for(t in e)"function"==typeof e[t]&&s.test(t)===!1&&(e[t]=l(e,t))},on:function(t,e){var n,r,i=this;for(t=t.split(" "),n=0;(r=t[n])!==a;n++)(i._listener[r]=i._listener[r]||[]).push(e);return i},one:function(t,e,n){n=n!==!1;var r=this;return r.on(t,function i(o){r.off(n===!0?o:t,i),e.apply(this,arguments)}),r},off:function(t,e){var n,r,i,o,l=this;if(t)for(t=t.split(" "),n=0;(r=t[n])!==a;n++)if(l._listener[r]=l._listener[r]||[],e)for(i=0;(o=l._listener[r][i])!==a;i++)o===e&&(l._listener[r].splice(i,1),i--);else l._listener[r].length=0;else for(r in l._listener)l._listener[r].length=0;return l},emit:function(t){var e,n,r=this;if(t!==a)for(r._listener[t]=r._listener[t]||[],e=0;(n=r._listener[t][e])!==a;e++)n.apply(r,arguments);return r}})});
(function(t){window.qoopido.registerSingleton("component/remux",t,["../emitter"])})(function(t,e,n,r,i,o){"use strict";function a(){var t=this;return f.fontsize=parseInt(i.getComputedStyle(l).getPropertyValue("font-size"),10),f.layout=i.getComputedStyle(l,":after").getPropertyValue("content")||null,(f.fontsize!==d.fontsize||f.layout!==d.layout)&&(d.fontsize=f.fontsize,d.layout=f.layout,f.ratio.device=i.devicePixelRatio||1,f.ratio.fontsize=f.fontsize/c,f.ratio.total=f.ratio.device*f.ratio.fontsize,t.emit("statechange",f)),t}var s,u,l=o.getElementsByTagName("html")[0],c=16,f={fontsize:null,layout:null,ratio:{}},d={fontsize:null,layout:null},p=null;return s=t.emitter.extend({_constructor:function(){var t=this,e=parseInt(l.getAttribute("data-base"),10),n=function n(){null!==p&&i.clearTimeout(p),p=i.setTimeout(function(){a.call(t)},20)};s._parent._constructor.call(t),isNaN(e)===!1&&(c=e),u=o.createElement("style"),u.type="text/css",o.getElementsByTagName("head")[0].appendChild(u),i.addEventListener("resize",n,!1),i.addEventListener("orientationchange",n,!1),a.call(t)},getState:function(){return f},addLayout:function(t,e){var n,r,i,s,l,f,d=this;arguments.length>1?(n={},n[t]=e):n=arguments[0];for(r in n)for(i=n[r],s=i.min;i.max>=s;s++)l=Math.round(i.width*(s/c)),f="@media screen and (min-width: "+l+"px) { html { font-size: "+s+'px; } html:after { content: "'+r+'"; display: none; } }',u.styleSheet?u.styleSheet.cssText+=f:u.appendChild(o.createTextNode(f));return a.call(d),d}})});